### ISSUE TITLE
Remove the square bracket from the attendant's name.

### ISSUE THREAD

**Issue by gomesOseias** [dudanogueira/rocket.connect#113]
I was thinking here about removing the bracket from the attendant's name when the customer is served.

Instead of [AgentName], keeping just "Agent Name", without the square bracket, would work better for me in WPPCONNECT.

Also, it would be interesting for the bot not to show its name, but when someone answers, show it.

**Comment by dudanogueira** [comment]
In 1.1.9 has a new option now, tudo configure it:

https://github.com/dudanogueira/rocket.connect/commit/cb3f08f205dff504286834e58d131f55a2327cb4
