### ISSUE TITLE
Reply

### ISSUE THREAD

**Issue by crashbr** [dudanogueira/rocket.connect#2]
Ao utilizar o comando de reply, o rocket encaminha um link ao invés da mensagem original.

![image](https://user-images.githubusercontent.com/2991052/114786256-3233c780-9d54-11eb-8790-a0a9fed66767.png)

**Comment by dudanogueira** [comment]
Fixed on latest release. As this is the first Issue, you will get a free beer at out next Rocket Connect Summit :P
