### ISSUE TITLE
Edição do nome do contato no Rocket.Chat

### ISSUE THREAD

**Issue by diegoromanio** [dudanogueira/rocket.connect#41]
Nas versões anteriores do Rocket.Connect, quais não informavam o nome do contato no WhatsApp, era possível editar o nome do contato no Rocket.Chat e nas próximas conversas aquele nome continuava, ajudando na identificação do cliente/empresa.
Hoje, com a alteração para que fosse possível identificar o nome que o contato tem no WhatsApp, essa opção de "editar" o nome ficou indisponível, se eu edito o nome no ROcket.Chat, nas próximas conversas é sobrescrito com as informações que vem do WhatsApp.

**Comment by dudanogueira** [comment]
Acho que essa opção vai fazer isso:
https://github.com/dudanogueira/rocket.connect/blob/dev/rocket_connect/plugins/base.py#L833

 overwrite_custom_fields = forms.BooleanField(
        required=False, help_text="overwrite custom fields on new visitor registration"
    )

![image](https://user-images.githubusercontent.com/1761174/151703286-3babf998-aacd-44da-b6b2-87f8a87cd9ed.png)

vou fechar, mas se precisar, pode abrir denovo!!!

**Comment by dudanogueira** [comment]
Agora sim. Havia uma opção não mapeada:
https://github.com/dudanogueira/rocket.connect/blob/dev/rocket_connect/plugins/base.py#L344
