### ISSUE TITLE
Problemas com mensagens "Grandes"

### ISSUE THREAD

**Issue by diegoromal** [dudanogueira/rocket.connect#42]
Ao enviar um vídeo, áudio, até mesmo um texto grande, o conector do wppconect trava e é preciso parar o container, "ler as mensagens" no whatsapp, e iniciar o container novamente.
Creio ser um problema com o wppconnect, estou investigando mais ingormações.

**Comment by dudanogueira** [comment]
resolvido na ultima 1.1.9. Existe um parametro que aumenta o tamanho do payload. Também resolve envio de arquivos de audio e video grandes
