### ISSUE TITLE
[FEATURE] Opções de verificar sessão via API

### ISSUE THREAD

**Issue by diegoromanio** [dudanogueira/rocket.connect#43]
Seria interessante termos uma opção para monitorar o wppconnect: sessão ativa, parar, iniciar, etc todas via api, assim pode ser implementado via Rocket.Chat essas funçoes e também usarmos em um sistema de monitoramento(zabbix).

**Comment by diegoromanio** [comment]
Além das questóes de sessão, acho interessante conseguirmos forçar as mensagens não enviadas via api também.

**Comment by dudanogueira** [comment]
closed by https://github.com/dudanogueira/rocket.connect/commit/5bb07be99e6e6706f7605382641c9f72a955ea9a
