### ISSUE TITLE
[FEATURE] Comandos para Inicializar e Fechar a Sessão do WPPConnect no canal Rocket.Connect

### ISSUE THREAD

**Issue by mtcoliveira** [dudanogueira/rocket.connect#46]
Verificar possiblidade de criar uma chamada via Canal (Rocket.Connect) no Rocket.Chat para Fechar a Sessão e também Inicializar a sessão via leitura de QRCode do WPPConnect pelo Rocket.Connect

**Comment by dudanogueira** [comment]
closed by https://github.com/dudanogueira/rocket.connect/commit/5bb07be99e6e6706f7605382641c9f72a955ea9a
