### ISSUE TITLE
[FIX] JSON WhatsApp Buttons - Tratamento da mensagem "In Response to"

### ISSUE THREAD

**Issue by mtcoliveira** [dudanogueira/rocket.connect#48]
Verificar um meio da mensagem (In Response to) ser enviada para o canal do Rocket.Chat só com o conteúdo do "displayText" do JSON.

![photo5170182237247875525](https://user-images.githubusercontent.com/25369411/151972679-846e5367-8d4b-41d8-aadb-a8f45cd346bd.jpg)

**Comment by dudanogueira** [comment]
closed in 0e449e067021c16fc8d94aef215582cfea030f41
